-- AlterTable
ALTER TABLE "AboutMeans" ALTER COLUMN "creatorId" DROP NOT NULL,
ALTER COLUMN "editorId" DROP NOT NULL;

-- AlterTable
ALTER TABLE "SeverityLevel" ALTER COLUMN "creatorId" DROP NOT NULL,
ALTER COLUMN "editorId" DROP NOT NULL;

-- AlterTable
ALTER TABLE "SortForce" ALTER COLUMN "creatorId" DROP NOT NULL,
ALTER COLUMN "editorId" DROP NOT NULL;

-- AlterTable
ALTER TABLE "SortGravity" ALTER COLUMN "creatorId" DROP NOT NULL,
ALTER COLUMN "editorId" DROP NOT NULL;
